/**
 * Small-screen gate: turns the phone breakpoint into a signpost instead of a
 * dead end.
 *
 * The gate itself is CSS-driven (see the < 768px tier in css/style.css); this
 * file only upgrades its primary call to action. A phone visitor who arrived
 * through a deep link -- typically a /library/ landing page CTA, or a shared
 * link -- gets sent to the landing page matching that link rather than to the
 * generic library index, so the trip does not end where it started.
 *
 * The param -> page slug lookup lives in library/library-map.js, generated by
 * dataset/generate_seo_pages.py alongside the pages themselves. If that file is
 * missing or carries no match, the markup's default (the library index) stands.
 */

(function () {
    'use strict';

    var PHONE_QUERY = '(max-width: 767px)';

    /** Resolve the deep link in the current URL to a landing page, if one exists. */
    function matchLandingPage(params, map) {
        var metricId = params.get('specificMetric');
        if (metricId && map.metrics && map.metrics[metricId]) {
            var metric = map.metrics[metricId];
            return {
                slug: metric.slug,
                label: 'Read about ' + metric.name,
                text: 'The metric you were opening, with its definition, sources, and the '
                    + 'frameworks and companies that reference it.'
            };
        }

        var framework = params.get('specificFramework');
        if (framework && map.frameworks && map.frameworks[framework]) {
            // "SPACE Framework" reads better as plain "SPACE" inside a sentence.
            var short = framework.replace(/\s*framework\s*$/i, '').trim() || framework;
            return {
                slug: map.frameworks[framework],
                label: 'Read the ' + short + ' collection',
                text: 'Every metric in the Compass associated with ' + short + ', with '
                    + 'definitions and sources.'
            };
        }

        var company = params.get('specificCompany');
        if (company && map.companies && map.companies[company]) {
            return {
                slug: map.companies[company],
                label: 'Read the ' + company + ' collection',
                text: 'The metrics reportedly used at ' + company + ', with definitions '
                    + 'and sources.'
            };
        }

        return null;
    }

    function applyDeepLink() {
        var map = window.LIBRARY_MAP;
        var card = document.getElementById('mobile-gate-library');
        if (!map || !card) { return; }

        var match = matchLandingPage(new URLSearchParams(window.location.search), map);
        if (!match) { return; }

        var href = 'library/' + match.slug + '.html';
        // Tapping a landing page's "open in the Compass" CTA is the common way to
        // reach the gate on a phone. Offering that same page back would be a loop,
        // so leave the default (the library index) in place instead.
        if (window.document.referrer
            && window.document.referrer.split('?')[0].split('#')[0]
                === new URL(href, window.location.href).href) {
            return;
        }

        card.href = href;
        document.getElementById('mobile-gate-library-label').textContent = match.label;
        document.getElementById('mobile-gate-library-text').textContent = match.text;
        // With the primary card now pointing at one page, offer the full index too.
        document.getElementById('mobile-gate-all-collections').hidden = false;
    }

    // Only phones ever see the gate; skip the work everywhere else.
    if (window.matchMedia && !window.matchMedia(PHONE_QUERY).matches) { return; }

    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', applyDeepLink);
    } else {
        applyDeepLink();
    }
})();
